export const lendingABI = [
	{
		inputs: [
			{
				internalType: "address",
				name: "initialOwner",
				type: "address",
			},
			{
				internalType: "address",
				name: "_debtToken",
				type: "address",
			},
			{
				internalType: "address",
				name: "_debtTokenPriceFeed",
				type: "address",
			},
			{
				internalType: "address",
				name: "_uniswapRouter",
				type: "address",
			},
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], name: "EnforcedPause", type: "error" },
	{ inputs: [], name: "ExpectedPause", type: "error" },
	{ inputs: [], name: "Lending__AccessDenied", type: "error" },
	{ inputs: [], name: "Lending__AmountExceedsLimit", type: "error" },
	{
		inputs: [],
		name: "Lending__CollateralRaisingAlreadyClosed",
		type: "error",
	},
	{
		inputs: [],
		name: "Lending__CollateralRaisingAlreadyOpen",
		type: "error",
	},
	{
		inputs: [],
		name: "Lending__CollateralRaisingTargetNotMet",
		type: "error",
	},
	{
		inputs: [],
		name: "Lending__CollateralRaisingTargetReached",
		type: "error",
	},
	{ inputs: [], name: "Lending__InsufficientCollateral", type: "error" },
	{ inputs: [], name: "Lending__InsufficientLiquidity", type: "error" },
	{ inputs: [], name: "Lending__InvalidAddress", type: "error" },
	{ inputs: [], name: "Lending__LTVViolation", type: "error" },
	{ inputs: [], name: "Lending__MustBeMoreThanZero", type: "error" },
	{ inputs: [], name: "Lending__NotLiquidatable", type: "error" },
	{ inputs: [], name: "Lending__OutstandingDebt", type: "error" },
	{ inputs: [], name: "Lending__PriceFeedNotAvailable", type: "error" },
	{ inputs: [], name: "Lending__TokenAlreadySupported", type: "error" },
	{ inputs: [], name: "Lending__TokenNotSupported", type: "error" },
	{ inputs: [], name: "Lending__UnsettledDebt", type: "error" },
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		name: "OwnableInvalidOwner",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "account", type: "address" }],
		name: "OwnableUnauthorizedAccount",
		type: "error",
	},
	{ inputs: [], name: "PriceFeedLib__StalePriceData", type: "error" },
	{ inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
	{
		inputs: [{ internalType: "address", name: "token", type: "address" }],
		name: "SafeERC20FailedOperation",
		type: "error",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "totalDebt",
				type: "uint256",
			},
		],
		name: "Borrowed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "funder",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "CollateralFunded",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
		],
		name: "CollateralRaisingClosed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "funder",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "CollateralRepayment",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "token",
				type: "address",
			},
			{
				indexed: false,
			internalType: "address",
				name: "priceFeed",
				type: "address",
			},
		],
		name: "CollateralTokenAdded",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "token",
				type: "address",
			},
		],
		name: "CollateralTokenRemoved",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "funder",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "InterestPaid",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "token",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "collateralSeized",
				type: "uint256",
			},
		],
		name: "Liquidated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint16",
				name: "newInterestRate",
				type: "uint16",
			},
			{
				indexed: false,
				internalType: "uint32",
				name: "newDurationLimit",
				type: "uint32",
			},
		],
		name: "LoanParamsChanged",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "address",
				name: "account",
				type: "address",
			},
		],
		name: "Paused",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "token",
				type: "address",
			},
			{
				indexed: false,
				internalType: "address",
				name: "newPriceFeed",
				type: "address",
			},
		],
		name: "PriceFeedUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "token",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint16",
				name: "interestRate",
				type: "uint16",
			},
		],
		name: "RaisingCollateral",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "user",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "Repaid",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
			internalType: "address",
				name: "account",
				type: "address",
			},
		],
		name: "Unpaused",
		type: "event",
	},
	{
		inputs: [],
		name: "BPS_DENOMINATOR",
		outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "DEFAULT_DECIMALS",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "HEALTH_FACTOR_THRESHOLD_BPS",
		outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "LIQUIDATION_PENALTY_BPS",
		outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "LTV_BPS",
		outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "PRICE_PRECISION",
		outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "PRICE_STALE_TIME",
		outputs: [{ internalType: "uint24", name: "", type: "uint24" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_token", type: "address" },
			{
				internalType: "address",
				name: "_priceFeed",
				type: "address",
			},
		],
		name: "addCollateralToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "closeCollateralRaising",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_token", type: "address" },
			{ internalType: "uint256", name: "_amount", type: "uint256" },
		],
		name: "depositCollateral",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
		name: "depositDebtToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_user", type: "address" },
			{ internalType: "uint256", name: "_amount", type: "uint256" },
		],
		name: "fundUser",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_token", type: "address" }],
		name: "getCollateralBalance",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getCollateralTokens",
		outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_user", type: "address" }],
		name: "getLoanInfo",
		outputs: [
			{
				components: [
					{
						internalType: "uint256",
						name: "debt",
						type: "uint256",
					},
					{
						internalType: "uint256",
						name: "repaid",
						type: "uint256",
					},
					{
						internalType: "uint256",
						name: "dueDate",
						type: "uint256",
					},
				],
				internalType: "struct Lending.Loan",
				name: "",
				type: "tuple",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_token", type: "address" }],
		name: "getPriceFeed",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_token", type: "address" }],
		name: "getTokenDecimals",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_user", type: "address" }],
		name: "getTotalCollateralValueInDebtToken",
		outputs: [
			{
				internalType: "uint256",
				name: "totalValue",
				type: "uint256",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_user", type: "address" }],
		name: "getUserCollateralRaisingInfo",
		outputs: [
			{ internalType: "bool", name: "isOpen", type: "bool" },
			{
				internalType: "address",
				name: "collateralToken",
				type: "address",
			},
			{ internalType: "uint256", name: "target", type: "uint256" },
			{ internalType: "uint256", name: "raised", type: "uint256" },
			{
				internalType: "uint256",
				name: "interestRateInBPS",
				type: "uint256",
			},
			{
				internalType: "address[]",
				name: "funders",
				type: "address[]",
			},
			{
				components: [
					{
						internalType: "uint256",
						name: "amount",
						type: "uint256",
					},
					{
						internalType: "uint256",
						name: "reward",
						type: "uint256",
					},
				],
				internalType: "struct Lending.FunderInfo[]",
				name: "funderInfo",
				type: "tuple[]",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "i_debtToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "i_debtTokenPriceFeed",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "i_uniswapRouter",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_user", type: "address" },
			{ internalType: "address", name: "_token", type: "address" },
		],
		name: "liquidate",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "pause",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "paused",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_token", type: "address" }],
		name: "removeCollateralToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_funder", type: "address" },
			{
				internalType: "uint256",
				name: "_collateralAmount",
				type: "uint256",
			},
			{
				internalType: "uint256",
				name: "_interestAmount",
				type: "uint256",
			},
		],
		name: "repayFunder",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
		name: "repayLoan",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "resetCollateralRaising",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		name: "s_collateralTokens",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "s_interestRateInBPS",
		outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "s_loanDurationLimit",
		outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint16", name: "_newRate", type: "uint16" },
			{
				internalType: "uint32",
				name: "_newDuration",
				type: "uint32",
			},
		],
		name: "setLoanParams",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_token", type: "address" },
			{ internalType: "uint256", name: "_target", type: "uint256" },
			{
				internalType: "uint16",
				name: "_interestRateBPS",
				type: "uint16",
			},
		],
		name: "startCollateralRaising",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
		name: "takeLoan",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "newOwner", type: "address" },
		],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "unpause",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_token", type: "address" },
			{
				internalType: "address",
				name: "_newPriceFeed",
				type: "address",
			},
		],
		name: "updatePriceFeed",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_token", type: "address" },
			{ internalType: "uint256", name: "_amount", type: "uint256" },
		],
		name: "withdrawCollateral",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
		name: "withdrawDebtToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
] as const;

// Contract helper functions
export const LENDING_CONTRACT_FUNCTIONS = {
  // Read functions
  GET_LOAN_INFO: "getLoanInfo",
  GET_COLLATERAL_BALANCE: "getCollateralBalance",
  GET_TOTAL_COLLATERAL_VALUE: "getTotalCollateralValueInDebtToken",
  GET_COLLATERAL_RAISING_INFO: "getUserCollateralRaisingInfo",
  GET_COLLATERAL_TOKENS: "getCollateralTokens",
  
  // Write functions
  START_COLLATERAL_RAISING: "startCollateralRaising",
  FUND_USER: "fundUser",
  CLOSE_COLLATERAL_RAISING: "closeCollateralRaising",
  TAKE_LOAN: "takeLoan",
  REPAY_LOAN: "repayLoan",
  DEPOSIT_COLLATERAL: "depositCollateral",
  WITHDRAW_COLLATERAL: "withdrawCollateral",
} as const;

export const LENDING_CONTRACT_EVENTS = {
  RAISING_COLLATERAL: "RaisingCollateral",
  COLLATERAL_FUNDED: "CollateralFunded",
  COLLATERAL_RAISING_CLOSED: "CollateralRaisingClosed",
  BORROWED: "Borrowed",
  REPAID: "Repaid",
  LIQUIDATED: "Liquidated",
} as const;
